/** Export verified research caches as a deterministic production TypeScript module. */
import { readFileSync, writeFileSync } from 'node:fs';

interface ToolCache { tools: Array<{ orbit: number; word: string[] }> }
interface OrientationCache { d4Orbit: number; examples: Array<{ word: string[] }> }

const tools = JSON.parse(
  readFileSync(new URL('./l3-global-tool-inventory.cache.json', import.meta.url), 'utf8'),
) as ToolCache;
const orientation = JSON.parse(
  readFileSync(new URL('./l3-orientation-tools.cache.json', import.meta.url), 'utf8'),
) as OrientationCache;

const output = `/* Generated by research/scratch/l3-export-solver-data.ts. */
/* Every word was independently verified globally pure by l3-global-tool-inventory.ts. */

export const level3PureToolWords: ReadonlyArray<{ orbit: number; word: readonly string[] }> = ${JSON.stringify(
  tools.tools.map(({ orbit, word }) => ({ orbit, word })),
  null,
  2,
)};

export const level3D4Orbit = ${orientation.d4Orbit};

export const level3D4TwisterWords: ReadonlyArray<readonly string[]> = ${JSON.stringify(
  orientation.examples.map(({ word }) => word),
  null,
  2,
)};
`;

writeFileSync(
  new URL('../../packages/solver-core/src/algorithms/level3SliceReductionToolData.ts', import.meta.url),
  output,
);
