/**
 * Shared plumbing for the Level 2 group-membership scripts: the atoms of G and
 * H, applying words of them with a legality check before every atom, exact
 * state comparison, and the orbit-wise parity invariant.
 *
 *   G — generated by the 468 existing legal atoms (`mengerPuzzleModel.legalMoves`).
 *   H — G's atoms plus the 54 additional square-ring atoms of
 *       `out/l2-extended-moves.json`, applied through synthetic `TurnTarget`s.
 *
 * Audit-only: nothing here changes the shipped model. Existing atoms are applied
 * through the solver model (so only shipped target ids can appear in a G-word);
 * additional atoms go through `applyExtensionRotation` with a target that
 * exists only in this module.
 */
import { readFileSync } from 'node:fs';
import { Matrix4, Vector3 } from 'three';
import type { Vector3Tuple } from 'three';
import { applyExtensionRotation, validateTurnTargetRotation } from '@menger/engine';
import type { Cubie, MengerPuzzleState, TurnTarget, TwistAngle } from '@menger/engine';
import type { SolverMove } from '@menger/solver-core';
import { mengerPuzzleModel } from '@menger/solver-core';
import { axisNames, cellKey, perpIndicesFor, pivot3D, targetForCells } from './model';
import type { AxisIndex, Candidate } from './model';

export const model = mengerPuzzleModel;
export const level = 2;
export const outDir = 'research/square-rotation/out';

interface ExtendedMovesFile {
  level: number;
  additional: Array<{
    id: string;
    family: string;
    axis: Vector3Tuple;
    pivot: Vector3Tuple;
    angle: TwistAngle;
    side: number;
    support: Vector3Tuple[];
  }>;
}

export interface AdditionalAtom {
  /** `<audit target id>@<angle>`, unique per atom. */
  key: string;
  targetId: string;
  axisIndex: AxisIndex;
  pivot: Vector3Tuple;
  angle: TwistAngle;
  side: number;
  supportSize: number;
  target: TurnTarget;
  targetById: Map<string, TurnTarget>;
}

/** A serialisable reference to one atom of H. */
export type AtomRef =
  | { kind: 'existing'; targetKind: 'frame' | 'extension'; id: string; angle: TwistAngle }
  | { kind: 'additional'; key: string };

export const solvedState = (): MengerPuzzleState => model.createState(level);

export const loadAdditionalAtoms = (): AdditionalAtom[] => {
  const file = JSON.parse(readFileSync(`${outDir}/l2-extended-moves.json`, 'utf8')) as ExtendedMovesFile;
  if (file.level !== level) throw new Error(`l2-extended-moves.json is for level ${file.level}`);
  return file.additional.map((entry) => {
    const axisIndex = entry.axis.findIndex((component) => component === 1) as AxisIndex;
    const [iu, iv] = perpIndicesFor[axisIndex];
    const candidate: Candidate = {
      id: `${entry.id}@${entry.angle}`,
      family: 'subset',
      axisIndex,
      axisName: axisNames[axisIndex],
      layers: [entry.pivot[axisIndex]!],
      pivot: pivot3D(axisIndex, entry.pivot[axisIndex]!, [entry.pivot[iu]!, entry.pivot[iv]!]),
      pivotInPlane: [entry.pivot[iu]!, entry.pivot[iv]!],
      regionSide: entry.side,
      cells: entry.support,
    };
    const target = targetForCells(candidate);
    return {
      key: `${entry.id}@${entry.angle}`,
      targetId: entry.id,
      axisIndex,
      pivot: entry.pivot,
      angle: entry.angle,
      side: entry.side,
      supportSize: entry.support.length,
      target,
      targetById: new Map([[target.id, target]]),
    };
  });
};

export const existingRef = (move: SolverMove): AtomRef => ({
  kind: 'existing',
  targetKind: move.targetKind as 'frame' | 'extension',
  id: move.targetKind === 'frame' ? move.frameId! : move.extensionTargetId!,
  angle: move.angle,
});

export const refLabel = (ref: AtomRef): string =>
  ref.kind === 'existing' ? `${ref.id}@${ref.angle}` : `+${ref.key}`;

export interface AtomTable {
  existing: SolverMove[];
  additional: AdditionalAtom[];
  additionalByKey: Map<string, AdditionalAtom>;
  existingByLabel: Map<string, SolverMove>;
}

export const buildAtomTable = (): AtomTable => {
  const existing = model.legalMoves(solvedState());
  const additional = loadAdditionalAtoms();
  return {
    existing,
    additional,
    additionalByKey: new Map(additional.map((atom) => [atom.key, atom])),
    existingByLabel: new Map(existing.map((move) => [refLabel(existingRef(move)), move])),
  };
};

/** The inverse of an atom is the same target at the negated angle (180 is self-inverse). */
export const inverseRef = (ref: AtomRef): AtomRef => {
  const negate = (angle: TwistAngle): TwistAngle => (angle === 180 ? 180 : (-angle as TwistAngle));
  if (ref.kind === 'existing') return { ...ref, angle: negate(ref.angle) };
  const [id, angle] = [ref.key.slice(0, ref.key.lastIndexOf('@')), Number(ref.key.slice(ref.key.lastIndexOf('@') + 1))];
  return { kind: 'additional', key: `${id}@${negate(angle as TwistAngle)}` };
};

/**
 * Applies one atom after asking the engine's judge. Existing atoms are looked
 * up in the state's own shipped target tables, so a G-word cannot smuggle in a
 * non-shipped target.
 */
export const applyRef = (state: MengerPuzzleState, ref: AtomRef, table: AtomTable): MengerPuzzleState => {
  if (ref.kind === 'existing') {
    const move = table.existingByLabel.get(refLabel(ref));
    if (!move) throw new Error(`unknown existing atom ${refLabel(ref)}`);
    if (!model.isMoveLegal(state, move)) throw new Error(`existing atom ${refLabel(ref)} judged illegal`);
    return model.applyMove(state, move);
  }
  const atom = table.additionalByKey.get(ref.key);
  if (!atom) throw new Error(`unknown additional atom ${ref.key}`);
  const verdict = validateTurnTargetRotation(state.cubies as Cubie[], atom.target, atom.angle);
  if (!verdict.legal) throw new Error(`additional atom ${ref.key} judged illegal: ${verdict.code}`);
  const cubies = applyExtensionRotation(state.cubies as Cubie[], atom.target.id, atom.angle, atom.targetById);
  return { ...state, cubies } as MengerPuzzleState;
};

export const applyWord = (state: MengerPuzzleState, word: readonly AtomRef[], table: AtomTable): MengerPuzzleState =>
  word.reduce((current, ref) => applyRef(current, ref, table), model.cloneState(state));

const orientationKey = (cubie: Cubie): string => {
  const matrix = new Matrix4().makeRotationFromQuaternion(cubie.orientation);
  return [new Vector3(1, 0, 0), new Vector3(0, 1, 0), new Vector3(0, 0, 1)]
    .map((axis) => axis.applyMatrix4(matrix))
    .map((axis) => [axis.x, axis.y, axis.z].map((value) => Math.round(value)).join(''))
    .join('|');
};

/**
 * Exact state record: for every cell (by home position), where it is and how
 * it is turned. H acts freely on these records (cells are distinguishable and
 * the solved record has trivial stabiliser), so equal keys mean equal group
 * elements.
 */
export const exactStateKey = (state: MengerPuzzleState): string =>
  [...(state.cubies as Cubie[])]
    .map((cubie) => `${cellKey(cubie.homePosition as Vector3Tuple)}>${cellKey(cubie.currentPosition as Vector3Tuple)}#${orientationKey(cubie)}`)
    .sort()
    .join(';');

export const isExactlySolved = (state: MengerPuzzleState): boolean =>
  (state.cubies as Cubie[]).every(
    (cubie) =>
      cellKey(cubie.homePosition as Vector3Tuple) === cellKey(cubie.currentPosition as Vector3Tuple) &&
      orientationKey(cubie) === '100|010|001',
  );

// --------------------------------------------------------- parity invariant

export interface ParityInvariant {
  siteIndex: Map<string, number>;
  orbitOfSite: number[];
  orbitSizes: number[];
  /** Orbit-wise sign vector of a state (bit k = odd permutation on orbit k). */
  vectorOf: (state: MengerPuzzleState) => number;
  /** Reduce a vector modulo a row-echelon basis; 0 iff it lies in the span. */
  reduce: (vector: number, basis: readonly number[]) => number;
  /** Row-echelon basis of the span of the given generators' vectors. */
  spanOf: (vectors: readonly number[]) => number[];
}

/** Site orbits of the group generated by `generatorStates` (each = one atom applied to solved). */
export const buildParityInvariant = (solved: MengerPuzzleState, generatorStates: MengerPuzzleState[]): ParityInvariant => {
  const sites = (solved.cubies as Cubie[]).map((cubie) => cellKey(cubie.currentPosition as Vector3Tuple));
  const siteIndex = new Map(sites.map((key, index) => [key, index]));
  const parent = sites.map((_, index) => index);
  const find = (index: number): number => {
    while (parent[index] !== index) {
      parent[index] = parent[parent[index]!]!;
      index = parent[index]!;
    }
    return index;
  };
  const permutationOf = (state: MengerPuzzleState): number[] => {
    const permutation = new Array<number>(sites.length);
    for (const cubie of state.cubies as Cubie[]) {
      permutation[siteIndex.get(cellKey(cubie.homePosition as Vector3Tuple))!] =
        siteIndex.get(cellKey(cubie.currentPosition as Vector3Tuple))!;
    }
    return permutation;
  };
  for (const state of generatorStates) {
    permutationOf(state).forEach((to, from) => {
      const [a, b] = [find(from), find(to)];
      if (a !== b) parent[a] = b;
    });
  }
  const rootToOrbit = new Map<number, number>();
  const orbitOfSite = sites.map((_, index) => {
    const root = find(index);
    if (!rootToOrbit.has(root)) rootToOrbit.set(root, rootToOrbit.size);
    return rootToOrbit.get(root)!;
  });
  const orbitSizes = new Array<number>(rootToOrbit.size).fill(0);
  for (const orbit of orbitOfSite) orbitSizes[orbit] += 1;

  const vectorOf = (state: MengerPuzzleState): number => {
    const permutation = permutationOf(state);
    const seen = new Array<boolean>(permutation.length).fill(false);
    let mask = 0;
    for (let start = 0; start < permutation.length; start += 1) {
      if (seen[start]) continue;
      let length = 0;
      for (let cursor = start; !seen[cursor]; cursor = permutation[cursor]!) {
        seen[cursor] = true;
        length += 1;
      }
      if (orbitOfSite[permutation[start]!] !== orbitOfSite[start]) {
        throw new Error('state moves a cell off its site orbit: the parity vector is undefined');
      }
      if (length % 2 === 0) mask ^= 1 << orbitOfSite[start]!;
    }
    return mask;
  };
  const reduce = (vector: number, basis: readonly number[]): number => {
    let residue = vector;
    for (const row of basis) if (residue & (row & -row)) residue ^= row;
    return residue;
  };
  const spanOf = (vectors: readonly number[]): number[] => {
    const basis: number[] = [];
    for (const vector of vectors) {
      const residue = reduce(vector, basis);
      // Each new row is reduced against the earlier ones, so it lacks their
      // pivot bits (lowest set bits); reducing in insertion order is then exact.
      if (residue !== 0) basis.push(residue);
    }
    return basis;
  };
  return { siteIndex, orbitOfSite, orbitSizes, vectorOf, reduce, spanOf };
};
