/**
 * Level 2: decide the index [H : G] with replay-verifiable certificates.
 *
 * Run: `node --import tsx research/square-rotation/index-certificate.ts`
 * (`INDEX_PILOT=<n>` stops after n non-trivial solves, to time the harness).
 * Writes `research/square-rotation/out/l2-index-certificate.json`; re-check it
 * with `verify-certificates.ts`, which trusts nothing but the engine.
 *
 * The argument.
 *
 * 1. Orbit-wise parity ε : H -> F2^11 is a homomorphism (H preserves the 11
 *    site orbits). Its image on G has rank r, on H rank r + 1, so
 *    ψ(h) = [ε(h) ∉ span ε(G)] is a surjective homomorphism H -> F2 with
 *    G ⊆ K := ker ψ. Hence [H : K] = 2 and [H : G] = 2 iff K ⊆ G.
 * 2. Schreier's lemma: with the transversal {1, a} of K in H (any atom a with
 *    ψ(a) = 1) and S the 522 atoms of H, K is generated by the words
 *        t · s · rep(t·s)^-1     (t ∈ {1, a}, s ∈ S),
 *    where rep(x) = 1 if ψ(x) = 0 and a otherwise.
 * 3. Each Schreier generator is shown to lie in G constructively: apply its
 *    H-word to the solved state, then find a word w of *existing* atoms with
 *    w · state = solved (by identity, by matching a single existing atom, or
 *    by the shipped `level2-slice-reduction` solver), and replay w through the
 *    engine with a legality check before every atom. H acts freely on the
 *    exact 400-cell position+orientation record, so this proves membership.
 *
 * If every Schreier generator is certified, K ⊆ G, so G = K and [H : G] = 2:
 * the extended model reaches exactly twice as many states as the old one, and
 * the new states are exactly those with ψ = 1. If any generator fails, the
 * script says so and the index stays undetermined (≥ 2).
 *
 * Solver successes here are membership certificates for these specific
 * elements only. They say nothing about solver completeness.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import type { MengerPuzzleState } from '@menger/engine';
import { level2SliceReductionAlgorithm, warmLevel2SliceReductionSolver } from '@menger/solver-core';
import {
  applyWord,
  buildAtomTable,
  buildParityInvariant,
  exactStateKey,
  existingRef,
  inverseRef,
  isExactlySolved,
  model,
  outDir,
  refLabel,
  solvedState,
} from './h-atoms';
import type { AtomRef } from './h-atoms';

if (process.env.INDEX_VERBOSE !== '1') console.debug = () => {};

const pilotLimit = process.env.INDEX_PILOT ? Number(process.env.INDEX_PILOT) : Number.POSITIVE_INFINITY;

type Method = 'identity' | 'single-existing-atom' | 'solver';

interface GeneratorRecord {
  /** Schreier generator as an H-word: t, s, and rep(t·s)^-1. */
  word: string[];
  t: '1' | 'a';
  s: string;
  psiOfTs: 0 | 1;
  /** Index of an earlier record with the same group element, if any. */
  duplicateOf?: number;
  parityInGSpan: boolean;
  method?: Method;
  /** A word of existing atoms taking the generator's state back to solved. */
  certificate?: string[];
  verified: boolean;
  solverMs?: number;
  note?: string;
}

const main = async (): Promise<void> => {
  const started = performance.now();
  const table = buildAtomTable();
  const solved = solvedState();
  const existingRefs: AtomRef[] = table.existing.map(existingRef);
  const additionalRefs: AtomRef[] = table.additional.map((atom) => ({ kind: 'additional', key: atom.key }));
  const allRefs = [...existingRefs, ...additionalRefs];
  console.log(`atoms: existing ${existingRefs.length}, additional ${additionalRefs.length}`);

  const stateOf = (word: AtomRef[]): MengerPuzzleState => applyWord(solved, word, table);
  const existingStates = existingRefs.map((ref) => stateOf([ref]));
  const additionalStates = additionalRefs.map((ref) => stateOf([ref]));

  const invariantG = buildParityInvariant(solved, existingStates);
  const invariant = buildParityInvariant(solved, [...existingStates, ...additionalStates]);
  // Canonical form of a partition: each site labelled by the first site of its orbit.
  const canonical = (orbitOfSite: number[]): number[] => orbitOfSite.map((orbit) => orbitOfSite.indexOf(orbit));
  const samePartition = canonical(invariantG.orbitOfSite).join() === canonical(invariant.orbitOfSite).join();
  if (!samePartition) throw new Error('G- and H-orbit partitions differ; this argument assumes they coincide');
  const spanG = invariant.spanOf(existingStates.map(invariant.vectorOf));
  const spanH = invariant.spanOf([...existingStates, ...additionalStates].map(invariant.vectorOf));
  console.log(`orbits ${invariant.orbitSizes.length}; parity rank G ${spanG.length}, H ${spanH.length}`);
  if (spanH.length !== spanG.length + 1) throw new Error('expected the parity rank to grow by exactly one');

  const psi = (state: MengerPuzzleState): 0 | 1 => (invariant.reduce(invariant.vectorOf(state), spanG) === 0 ? 0 : 1);
  const psiOfRef = new Map(allRefs.map((ref, index) => [
    refLabel(ref),
    psi(index < existingRefs.length ? existingStates[index]! : additionalStates[index - existingRefs.length]!),
  ]));
  const a = additionalRefs.find((ref) => psiOfRef.get(refLabel(ref)) === 1)!;
  const aInverse = inverseRef(a);
  const psiOneAtoms = allRefs.filter((ref) => psiOfRef.get(refLabel(ref)) === 1).map(refLabel);
  console.log(`transversal element a = ${refLabel(a)}; atoms with ψ = 1: ${psiOneAtoms.length}`);

  // Lookup: exact state of every single existing atom, for the cheap certificate.
  const existingByStateKey = new Map<string, AtomRef>();
  existingStates.forEach((state, index) => existingByStateKey.set(exactStateKey(state), existingRefs[index]!));

  warmLevel2SliceReductionSolver();

  const records: GeneratorRecord[] = [];
  const firstByKey = new Map<string, number>();
  let solverRuns = 0;
  let solverMs = 0;
  for (const t of ['1', 'a'] as const) {
    for (const s of allRefs) {
      if (solverRuns >= pilotLimit) break;
      const prefix: AtomRef[] = t === '1' ? [] : [a];
      const psiTs = ((t === '1' ? 0 : 1) ^ psiOfRef.get(refLabel(s))!) as 0 | 1;
      const word: AtomRef[] = [...prefix, s, ...(psiTs === 1 ? [aInverse] : [])];
      const state = stateOf(word);
      const key = exactStateKey(state);
      const record: GeneratorRecord = {
        word: word.map(refLabel),
        t,
        s: refLabel(s),
        psiOfTs: psiTs,
        parityInGSpan: invariant.reduce(invariant.vectorOf(state), spanG) === 0,
        verified: false,
      };
      const earlier = firstByKey.get(key);
      if (earlier !== undefined) {
        record.duplicateOf = earlier;
        record.verified = records[earlier]!.verified;
        records.push(record);
        continue;
      }
      firstByKey.set(key, records.length);

      let certificate: AtomRef[] | null = null;
      if (isExactlySolved(state)) {
        record.method = 'identity';
        certificate = [];
      } else if (existingByStateKey.has(key)) {
        record.method = 'single-existing-atom';
        certificate = [inverseRef(existingByStateKey.get(key)!)];
      } else if (!record.parityInGSpan) {
        record.note = 'parity outside span ε(G): provably not in G';
      } else {
        record.method = 'solver';
        const solveStart = performance.now();
        const result = await level2SliceReductionAlgorithm.solve(model, model.cloneState(state));
        record.solverMs = Math.round(performance.now() - solveStart);
        solverMs += record.solverMs;
        solverRuns += 1;
        if (result.success) certificate = result.output_moves.map(existingRef);
        else record.note = `solver failed: ${result.notes.slice(0, 160)}`;
      }

      if (certificate) {
        try {
          const replayed = applyWord(state, certificate, table);
          record.verified = isExactlySolved(replayed);
          if (!record.verified) record.note = 'replay did not end exactly solved';
        } catch (error) {
          record.note = `replay failed: ${(error as Error).message}`;
        }
        record.certificate = certificate.map(refLabel);
      }
      records.push(record);
      if (record.method === 'solver') {
        process.stdout.write(
          `  [${String(records.length).padStart(4)}] ${record.word.join(' ').padEnd(70)} ` +
            `${record.verified ? `OK ${String(record.certificate!.length).padStart(4)} atoms` : 'FAIL'} ${record.solverMs}ms\n`,
        );
      }
    }
  }

  const unique = records.filter((record) => record.duplicateOf === undefined);
  const byMethod = (method: Method) => unique.filter((record) => record.method === method).length;
  const failures = unique.filter((record) => !record.verified);
  const complete = records.length === 2 * allRefs.length;
  const proved = complete && failures.length === 0;
  const lengths = unique.filter((record) => record.method === 'solver' && record.verified).map((r) => r.certificate!.length).sort((x, y) => x - y);
  const elapsedMs = Math.round(performance.now() - started);
  const heapMb = Math.round(process.memoryUsage().heapUsed / 1e6);

  console.log(
    `\nSchreier generators ${records.length} (${unique.length} distinct elements): identity ${byMethod('identity')}, ` +
      `single existing atom ${byMethod('single-existing-atom')}, solver ${byMethod('solver')}; unverified ${failures.length}`,
  );
  if (lengths.length > 0) {
    console.log(`solver certificate length min ${lengths[0]} median ${lengths[Math.floor(lengths.length / 2)]} max ${lengths.at(-1)}`);
  }
  console.log(`solver time ${solverMs}ms over ${solverRuns} runs; total ${elapsedMs}ms; heap ${heapMb}MB`);
  console.log(
    proved
      ? 'RESULT: every Schreier generator of K = ker ψ is certified in G, so G = K and [H : G] = 2 (proved).'
      : `RESULT: ${complete ? `${failures.length} generators not certified` : 'pilot run (incomplete)'}; [H : G] undetermined beyond ≥ 2.`,
  );

  mkdirSync(outDir, { recursive: true });
  const outPath = `${outDir}/l2-index-certificate.json`;
  writeFileSync(
    outPath,
    `${JSON.stringify(
      {
        level: 2,
        generatedAt: new Date().toISOString(),
        pilot: !complete,
        argument:
          'ψ = [ε(h) ∉ span ε(G)] is a surjective homomorphism H -> F2 with G ⊆ ker ψ. Schreier generators of ker ψ for ' +
          'the transversal {1, a} are t·s·rep(t·s)^-1. Each is certified in G by a word of existing atoms replayed through ' +
          'the engine to the exact solved state. All certified => G = ker ψ => [H:G] = 2.',
        wordConvention: 'Words are applied left to right to the solved state; `+<key>` is an additional atom, `<id>@<angle>` an existing one.',
        orbitSizes: invariant.orbitSizes,
        parityRank: { G: spanG.length, H: spanH.length },
        spanGBasis: spanG,
        transversal: refLabel(a),
        transversalInverse: refLabel(aInverse),
        psiOneAtoms,
        counts: {
          schreierGenerators: records.length,
          distinctElements: unique.length,
          identity: byMethod('identity'),
          singleExistingAtom: byMethod('single-existing-atom'),
          solver: byMethod('solver'),
          unverified: failures.length,
        },
        timing: { totalMs: elapsedMs, solverMs, solverRuns, heapMb },
        result: proved ? 'index-2-proved' : complete ? 'undetermined' : 'pilot',
        records,
      },
      null,
      1,
    )}\n`,
  );
  console.log(`wrote ${outPath}`);
};

await main();
