/**
 * Phase 2 of the square-rotation audit: do the *shipped* Level 2 solvers cope
 * with states produced by the 54 additional square-ring rotations?
 *
 * Run: `node --import tsx research/square-rotation/solver-trials.ts` from the
 * repo root. Writes `research/square-rotation/out/l2-solver-trials.json`.
 * Set `TRIALS_PILOT=1` for a short smoke run (3 single-move states, one seed
 * per word length) used only to time the harness.
 *
 * Nothing here changes the shipped model. The solvers are driven through
 * `mengerPuzzleModel`, whose `legalMoves` returns the 468 *existing* atoms
 * only, so every solution word lies in `G` by construction. The additional
 * atoms are applied outside the model, via synthetic `TurnTarget`s built by
 * `targetForCells`, exactly as the Phase 1 audit did.
 *
 * Definitions used throughout:
 *   G — the group generated by the 468 existing legal atomic moves.
 *   H — the group generated by those 468 plus the 54 additional atoms.
 *
 * Two independent, *rigorous* non-membership tests are run on every scrambled
 * state before any solver sees it (see `buildInvariants`): a site-orbit test
 * and an orbit-wise permutation-parity test. Both are homomorphic invariants
 * of G, so a state failing either is provably outside G; passing both proves
 * nothing. A solver success, replayed and verified here, is a constructive
 * membership certificate; no finite number of them is a completeness proof.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { Matrix4, Vector3 } from 'three';
import type { Vector3Tuple } from 'three';
import { applyExtensionRotation, validateTurnTargetRotation } from '@menger/engine';
import type { Cubie, MengerPuzzleState, TurnTarget, TwistAngle } from '@menger/engine';
import type { SolverMove, SolverRunResult } from '@menger/solver-core';
import {
  createSeededRng,
  level2BlockQuotientAlgorithm,
  level2SliceReductionAlgorithm,
  mengerPuzzleModel,
  warmLevel2SliceReductionSolver,
} from '@menger/solver-core';
import { axisNames, cellKey, perpIndicesFor, pivot3D, targetForCells } from './model';
import type { AxisIndex, Candidate } from './model';

// The solvers emit phase-boundary events on `console.debug` unconditionally.
// A few hundred solves drown the table in them, so mute that channel unless
// asked; the solver's own `notes`/`explanation` are captured either way.
if (process.env.TRIALS_VERBOSE !== '1') console.debug = () => {};

const pilot = process.env.TRIALS_PILOT === '1';
const outDir = 'research/square-rotation/out';
const outPath = `${outDir}/l2-solver-trials.json`;
const level = 2;
const model = mengerPuzzleModel;

// ---------------------------------------------------------------- the atoms

const solved = model.createState(level);
const existingAtoms: SolverMove[] = model.legalMoves(solved);

/**
 * The 18 additional targets x 3 angles, read back from the Phase 1 audit
 * output (`l2-extended-moves.json`) so this script tests exactly the move set
 * that audit certified, not a re-derivation of it. Each entry is turned into a
 * synthetic `TurnTarget` by the same `targetForCells` the audit used.
 */
interface ExtendedMovesFile {
  level: number;
  cells: Vector3Tuple[];
  existing: Array<{ id: string; axis: Vector3Tuple; pivot: Vector3Tuple; angle: TwistAngle; support: Vector3Tuple[] }>;
  additional: Array<{
    id: string;
    family: string;
    axis: Vector3Tuple;
    pivot: Vector3Tuple;
    angle: TwistAngle;
    side: number;
    support: Vector3Tuple[];
  }>;
}

interface AdditionalAtom {
  id: string;
  family: string;
  axisIndex: AxisIndex;
  angle: TwistAngle;
  /** Bounding-box side of the ring: 5 (inner) or 9 (outer). */
  side: number;
  supportSize: number;
  target: TurnTarget;
  targetById: Map<string, TurnTarget>;
}

const extended = JSON.parse(readFileSync(`${outDir}/l2-extended-moves.json`, 'utf8')) as ExtendedMovesFile;
if (extended.level !== level) throw new Error(`the audit file is for level ${extended.level}, not ${level}`);

const additionalAtoms: AdditionalAtom[] = extended.additional.map((entry) => {
  const axisIndex = entry.axis.findIndex((component) => component === 1) as AxisIndex;
  const [iu, iv] = perpIndicesFor[axisIndex];
  const candidate: Candidate = {
    // The target id must be unique per (support, angle): the same ring rotated
    // by two different angles is two different atoms in this harness.
    id: `${entry.id}@${entry.angle}`,
    family: 'subset',
    axisIndex,
    axisName: axisNames[axisIndex],
    layers: [entry.pivot[axisIndex]!],
    pivot: pivot3D(axisIndex, entry.pivot[axisIndex]!, [entry.pivot[iu]!, entry.pivot[iv]!]),
    pivotInPlane: [entry.pivot[iu]!, entry.pivot[iv]!],
    regionSide: entry.side,
    cells: entry.support,
  };
  const target = targetForCells(candidate) as unknown as TurnTarget;
  return {
    id: entry.id,
    family: entry.family,
    axisIndex,
    angle: entry.angle,
    side: entry.side,
    supportSize: entry.support.length,
    target,
    targetById: new Map([[target.id, target]]),
  };
});

/** Applies one additional atom, refusing to continue if the judge says no. */
const applyAdditional = (state: MengerPuzzleState, atom: AdditionalAtom): MengerPuzzleState => {
  const verdict = validateTurnTargetRotation(state.cubies as Cubie[], atom.target, atom.angle);
  if (!verdict.legal) {
    throw new Error(`additional atom ${atom.id}@${atom.angle} judged illegal: ${verdict.code}`);
  }
  const cubies = applyExtensionRotation(state.cubies as Cubie[], atom.target.id, atom.angle, atom.targetById);
  if (cubies === state.cubies) throw new Error(`additional atom ${atom.id}@${atom.angle} was a no-op`);
  return { ...state, cubies } as MengerPuzzleState;
};

// ------------------------------------------------- exact-solution predicate

const identityOrientation = '100|010|001';

const orientationKey = (cubie: Cubie): string => {
  const matrix = new Matrix4().makeRotationFromQuaternion(cubie.orientation);
  return [new Vector3(1, 0, 0), new Vector3(0, 1, 0), new Vector3(0, 0, 1)]
    .map((axis) => axis.applyMatrix4(matrix))
    .map((axis) => [axis.x, axis.y, axis.z].map((value) => Math.round(value)).join(''))
    .join('|');
};

/**
 * Independent of the solver's own `isSolved`: all 400 cells must be at their
 * home position with the identity orientation.
 */
const exactAgreement = (cubies: readonly Cubie[]): { ok: boolean; cells: number; wrongPosition: number; wrongOrientation: number } => {
  let wrongPosition = 0;
  let wrongOrientation = 0;
  for (const cubie of cubies) {
    const current = cubie.currentPosition as Vector3Tuple;
    const home = cubie.homePosition as Vector3Tuple;
    if (cellKey(current) !== cellKey(home)) wrongPosition += 1;
    if (orientationKey(cubie) !== identityOrientation) wrongOrientation += 1;
  }
  return { ok: wrongPosition === 0 && wrongOrientation === 0, cells: cubies.length, wrongPosition, wrongOrientation };
};

// -------------------------------------------------- rigorous G-invariants

/**
 * Two homomorphic invariants of G, computed from the 468 existing atoms:
 *
 * 1. **Site orbits.** The orbits of G on the 400 sites are the connected
 *    components of the graph "some generator sends site p to site q". G
 *    preserves them, so in any state reachable from solved every cell sits in
 *    the orbit of its own home site.
 * 2. **Orbit-wise parity.** Each orbit is G-invariant, so restricting a group
 *    element to one orbit gives a permutation; its sign is a homomorphism
 *    G -> {+-1}, and collecting all orbits gives G -> F2^k. The image of a
 *    generated group under a homomorphism into an abelian group is the span of
 *    the generators' images, so a reachable state's sign vector must lie in the
 *    F2-span of the 468 generator sign vectors.
 *
 * Failing either test proves the state is outside G. Passing both proves
 * nothing: these are necessary conditions only (orientation freedom, in
 * particular, is not tested at all).
 */
interface Invariants {
  siteIndex: Map<string, number>;
  orbitOfSite: number[];
  orbitSizes: number[];
  /** Row-reduced basis of the generators' sign vectors, as bitmasks. */
  parityBasis: number[];
  parityRank: number;
}

const buildInvariants = (): Invariants => {
  const sites = solved.cubies.map((cubie) => cellKey(cubie.currentPosition as Vector3Tuple));
  const siteIndex = new Map(sites.map((key, index) => [key, index]));
  const parent = sites.map((_, index) => index);
  const find = (index: number): number => {
    let root = index;
    while (parent[root] !== root) root = parent[root]!;
    let walk = index;
    while (parent[walk] !== walk) {
      const next = parent[walk]!;
      parent[walk] = root;
      walk = next;
    }
    return root;
  };
  const union = (a: number, b: number): void => {
    const ra = find(a);
    const rb = find(b);
    if (ra !== rb) parent[ra] = rb;
  };

  // Each generator's site permutation, read off by applying it to the solved state.
  const permutations: number[][] = [];
  for (const move of existingAtoms) {
    const next = model.applyMove(solved, move);
    const permutation = new Array<number>(sites.length);
    for (const cubie of next.cubies) {
      const from = siteIndex.get(cellKey(cubie.homePosition as Vector3Tuple))!;
      const to = siteIndex.get(cellKey(cubie.currentPosition as Vector3Tuple))!;
      permutation[from] = to;
      union(from, to);
    }
    permutations.push(permutation);
  }

  const rootToOrbit = new Map<number, number>();
  const orbitOfSite = sites.map((_, index) => {
    const root = find(index);
    if (!rootToOrbit.has(root)) rootToOrbit.set(root, rootToOrbit.size);
    return rootToOrbit.get(root)!;
  });
  const orbitCount = rootToOrbit.size;
  const orbitSizes = new Array<number>(orbitCount).fill(0);
  for (const orbit of orbitOfSite) orbitSizes[orbit] += 1;

  const signVector = (permutation: number[]): number => {
    const seen = new Array<boolean>(permutation.length).fill(false);
    const oddCycles = new Array<number>(orbitCount).fill(0);
    for (let start = 0; start < permutation.length; start += 1) {
      if (seen[start]) continue;
      let length = 0;
      let cursor = start;
      while (!seen[cursor]) {
        seen[cursor] = true;
        cursor = permutation[cursor]!;
        length += 1;
      }
      // A cycle of length L contributes (L-1) transpositions.
      if ((length - 1) % 2 === 1) oddCycles[orbitOfSite[start]!] += 1;
    }
    let mask = 0;
    for (let orbit = 0; orbit < orbitCount; orbit += 1) {
      if (oddCycles[orbit]! % 2 === 1) mask |= 1 << orbit;
    }
    return mask;
  };

  const parityBasis: number[] = [];
  for (const permutation of permutations) {
    let vector = signVector(permutation);
    for (const basis of parityBasis) {
      const pivotBit = basis & -basis;
      if (vector & pivotBit) vector ^= basis;
    }
    if (vector !== 0) parityBasis.push(vector);
  }

  return { siteIndex, orbitOfSite, orbitSizes, parityBasis, parityRank: parityBasis.length };
};

const invariants = buildInvariants();

const signVectorOfState = (cubies: readonly Cubie[]): number => {
  const permutation = new Array<number>(cubies.length);
  for (const cubie of cubies) {
    const from = invariants.siteIndex.get(cellKey(cubie.homePosition as Vector3Tuple))!;
    const to = invariants.siteIndex.get(cellKey(cubie.currentPosition as Vector3Tuple))!;
    permutation[from] = to;
  }
  const orbitCount = invariants.orbitSizes.length;
  const seen = new Array<boolean>(permutation.length).fill(false);
  const oddCycles = new Array<number>(orbitCount).fill(0);
  for (let start = 0; start < permutation.length; start += 1) {
    if (seen[start]) continue;
    let length = 0;
    let cursor = start;
    while (!seen[cursor]) {
      seen[cursor] = true;
      cursor = permutation[cursor]!;
      length += 1;
    }
    if ((length - 1) % 2 === 1) oddCycles[invariants.orbitOfSite[start]!] += 1;
  }
  let mask = 0;
  for (let orbit = 0; orbit < orbitCount; orbit += 1) {
    if (oddCycles[orbit]! % 2 === 1) mask |= 1 << orbit;
  }
  return mask;
};

interface InvariantVerdict {
  orbitConsistent: boolean;
  offOrbitCells: number;
  parityMask: number;
  parityInSpan: boolean;
  /** True only when an invariant *proves* the state is outside G. */
  provablyOutsideG: boolean;
}

const checkInvariants = (cubies: readonly Cubie[]): InvariantVerdict => {
  let offOrbitCells = 0;
  for (const cubie of cubies) {
    const home = invariants.orbitOfSite[invariants.siteIndex.get(cellKey(cubie.homePosition as Vector3Tuple))!]!;
    const current = invariants.orbitOfSite[invariants.siteIndex.get(cellKey(cubie.currentPosition as Vector3Tuple))!]!;
    if (home !== current) offOrbitCells += 1;
  }
  const parityMask = signVectorOfState(cubies);
  let residue = parityMask;
  for (const basis of invariants.parityBasis) {
    const pivotBit = basis & -basis;
    if (residue & pivotBit) residue ^= basis;
  }
  const parityInSpan = residue === 0;
  return {
    orbitConsistent: offOrbitCells === 0,
    offOrbitCells,
    parityMask,
    parityInSpan,
    provablyOutsideG: offOrbitCells > 0 || !parityInSpan,
  };
};

// --------------------------------------------------------- the trial runner

type FailureClass =
  | 'none'
  | 'i:outside-G-proved'
  | 'ii:illegal-atom-in-word'
  | 'iii:orbit-or-parity-mismatch'
  | 'iv:search-cutoff'
  // A refinement of bucket (v): the solver declined honestly because the state
  // is outside its *declared* scope, not because anything went wrong.
  | 'v:out-of-declared-scope'
  | 'v:unclassified';

interface SolveRecord {
  solver: string;
  success: boolean;
  moveCount: number;
  runtimeMs: number;
  replayVerified: boolean;
  replayDetail: string;
  failureClass: FailureClass;
  /**
   * True when the solver declined honestly because the state is outside its
   * *declared* scope rather than outside G — `level2-block-quotient` only
   * handles block-rigid states, so it rejects almost everything here by
   * design. Such a rejection is correct behaviour, not a solver defect.
   */
  declaredScopeRejection: boolean;
  notes: string;
}

/** The block-quotient solver's own wording for "this state is not block-rigid". */
const scopeRejectionPattern = /block region|block boundaries|block-rigid|rigidity|macro level 1/i;

interface TrialRecord {
  category: string;
  label: string;
  /** Ring geometry, for the single-additional trials only. */
  atom?: { id: string; angle: TwistAngle; side: number; supportSize: number };
  scrambleLength: number;
  invariant: InvariantVerdict;
  scrambleOk: boolean;
  scrambleNote: string;
  solves: SolveRecord[];
}

/** Replays a solution through the real engine, judging every move first. */
const replay = (scrambled: MengerPuzzleState, moves: readonly SolverMove[]): { ok: boolean; detail: string } => {
  let current = model.cloneState(scrambled);
  for (const [index, move] of moves.entries()) {
    if (!model.isMoveLegal(current, move)) {
      return { ok: false, detail: `move ${index} (${move.notation}) illegal in the state it is applied to` };
    }
    current = model.applyMove(current, move);
  }
  const agreement = exactAgreement(current.cubies as Cubie[]);
  if (!agreement.ok) {
    return {
      ok: false,
      detail: `replay ended off-solved: ${agreement.wrongPosition} cells misplaced, ${agreement.wrongOrientation} misoriented (of ${agreement.cells})`,
    };
  }
  return { ok: true, detail: `${agreement.cells}/400 cells exact` };
};

const classify = (
  result: SolverRunResult,
  replayResult: { ok: boolean; detail: string },
  invariant: InvariantVerdict,
): FailureClass => {
  if (result.success && replayResult.ok) return 'none';
  if (invariant.provablyOutsideG) return 'i:outside-G-proved';
  if (!replayResult.ok && replayResult.detail.includes('illegal in the state')) return 'ii:illegal-atom-in-word';
  const notes = `${result.notes} ${result.final_strategy}`.toLowerCase();
  if (/parit|orbit/.test(notes)) return 'iii:orbit-or-parity-mismatch';
  if (/cap|budget|cut ?off|exhaust|limit|no placement|gave up|timeout|depth/.test(notes)) return 'iv:search-cutoff';
  if (scopeRejectionPattern.test(result.notes)) return 'v:out-of-declared-scope';
  return 'v:unclassified';
};

const runSolvers = async (scrambled: MengerPuzzleState, invariant: InvariantVerdict): Promise<SolveRecord[]> => {
  const records: SolveRecord[] = [];
  for (const algorithm of [level2SliceReductionAlgorithm, level2BlockQuotientAlgorithm]) {
    const started = performance.now();
    const result = await algorithm.solve(model, model.cloneState(scrambled));
    const runtimeMs = performance.now() - started;
    const replayResult = result.success ? replay(scrambled, result.output_moves) : { ok: false, detail: 'no solution returned' };
    records.push({
      solver: algorithm.id,
      success: result.success,
      moveCount: result.move_count,
      runtimeMs,
      replayVerified: result.success && replayResult.ok,
      replayDetail: replayResult.detail,
      failureClass: classify(result, replayResult, invariant),
      declaredScopeRejection: !result.success && scopeRejectionPattern.test(result.notes),
      notes: result.notes.slice(0, 200),
    });
  }
  return records;
};

// -------------------------------------------------------------- word making

type WordAtom = { kind: 'existing'; move: SolverMove } | { kind: 'additional'; atom: AdditionalAtom };

const buildWord = (rng: () => number, length: number, pool: WordAtom[]): WordAtom[] =>
  Array.from({ length }, () => pool[Math.floor(rng() * pool.length)]!);

/** Applies a word, refusing any atom the engine's judge rejects in situ. */
const applyWord = (word: WordAtom[]): { state: MengerPuzzleState; ok: boolean; note: string } => {
  let state = solved;
  for (const [index, entry] of word.entries()) {
    if (entry.kind === 'existing') {
      if (!model.isMoveLegal(state, entry.move)) {
        return { state, ok: false, note: `word position ${index}: existing atom ${entry.move.notation} illegal in situ` };
      }
      state = model.applyMove(state, entry.move);
    } else {
      try {
        state = applyAdditional(state, entry.atom);
      } catch (error) {
        return { state, ok: false, note: `word position ${index}: ${(error as Error).message}` };
      }
    }
  }
  return { state, ok: true, note: 'all atoms legal in situ' };
};

// -------------------------------------------------------------------- trials

const trials: TrialRecord[] = [];
const categoryTimings = new Map<string, number>();

const runTrial = async (category: string, label: string, word: WordAtom[], atom?: AdditionalAtom): Promise<void> => {
  const started = performance.now();
  const applied = applyWord(word);
  const invariant = checkInvariants(applied.state.cubies as Cubie[]);
  const solves = applied.ok
    ? await runSolvers(applied.state, invariant)
    : [level2SliceReductionAlgorithm, level2BlockQuotientAlgorithm].map((algorithm) => ({
        solver: algorithm.id,
        success: false,
        moveCount: 0,
        runtimeMs: 0,
        replayVerified: false,
        replayDetail: 'not attempted: the scramble word contained an atom the judge rejected',
        failureClass: 'ii:illegal-atom-in-word' as FailureClass,
        declaredScopeRejection: false,
        notes: applied.note,
      }));
  trials.push({
    category,
    label,
    atom: atom && { id: atom.id, angle: atom.angle, side: atom.side, supportSize: atom.supportSize },
    scrambleLength: word.length,
    invariant,
    scrambleOk: applied.ok,
    scrambleNote: applied.note,
    solves,
  });
  categoryTimings.set(category, (categoryTimings.get(category) ?? 0) + (performance.now() - started));
  const line = solves
    .map((record) => `${record.solver === 'level2-slice-reduction' ? 'slice' : 'block'}=${record.replayVerified ? `OK/${record.moveCount}` : record.success ? 'UNVERIFIED' : 'fail'}`)
    .join(' ');
  console.log(
    `  ${label.padEnd(30)} len=${String(word.length).padStart(3)} orbit=${invariant.orbitConsistent ? 'ok' : `off:${invariant.offOrbitCells}`} parity=${invariant.parityInSpan ? 'in' : 'OUT'} ${line}`,
  );
};

const main = async (): Promise<void> => {
  console.log(`=== Level ${level} solver trials against the additional square-ring rotations ===`);
  console.log(
    `existing atoms exposed by mengerPuzzleModel.legalMoves: ${existingAtoms.length} ` +
      `(audit file lists ${extended.existing.length}${existingAtoms.length === extended.existing.length ? ', agrees' : ', DISAGREES'})`,
  );
  console.log(
    `additional atoms rebuilt: ${additionalAtoms.length} (${new Set(additionalAtoms.map((atom) => atom.id)).size} targets x 3 angles)`,
  );
  console.log(
    `G site orbits: ${invariants.orbitSizes.length} of sizes [${invariants.orbitSizes.join(', ')}]; parity image rank ${invariants.parityRank} of ${invariants.orbitSizes.length}`,
  );
  const warmStart = performance.now();
  warmLevel2SliceReductionSolver();
  const warmMs = performance.now() - warmStart;
  console.log(`warmed the slice-reduction commutator library in ${warmMs.toFixed(0)}ms\n`);

  // Trial 1 — the decisive one: a single additional atom on the solved state.
  console.log('--- trial 1: one additional atom applied to the solved state ---');
  const singles = pilot ? additionalAtoms.slice(0, 3) : additionalAtoms;
  for (const atom of singles) {
    await runTrial('single-additional', `${atom.id}@${atom.angle}`, [{ kind: 'additional', atom }], atom);
  }

  // Trial 2 — random words over the additional atoms only.
  console.log('\n--- trial 2: random words over the 54 additional atoms only ---');
  const additionalPool: WordAtom[] = additionalAtoms.map((atom) => ({ kind: 'additional', atom }));
  const seeds2 = pilot ? [101] : [101, 102, 103];
  for (const length of pilot ? [5] : [5, 10, 20]) {
    for (const seed of seeds2) {
      await runTrial('additional-only', `add-only len${length} seed${seed}`, buildWord(createSeededRng(seed + length * 1000), length, additionalPool));
    }
  }

  // Trial 3 — random words over existing + additional atoms.
  console.log('\n--- trial 3: random words over existing + additional atoms ---');
  const mixedPool: WordAtom[] = [
    ...existingAtoms.map((move) => ({ kind: 'existing' as const, move })),
    ...additionalPool,
  ];
  const seeds3 = pilot ? [201] : [201, 202, 203];
  for (const length of pilot ? [20] : [20, 50, 100]) {
    for (const seed of seeds3) {
      await runTrial('mixed', `mixed len${length} seed${seed}`, buildWord(createSeededRng(seed + length * 1000), length, mixedPool));
    }
  }

  // ------------------------------------------------------------- reporting
  const categories = [...new Set(trials.map((trial) => trial.category))];
  const summary = categories.flatMap((category) => {
    const rows = trials.filter((trial) => trial.category === category);
    return ['level2-slice-reduction', 'level2-block-quotient'].map((solver) => {
      const records = rows.map((row) => row.solves.find((solve) => solve.solver === solver)!);
      const failures = records.filter((record) => !record.replayVerified);
      const byClass = new Map<string, number>();
      for (const record of failures) byClass.set(record.failureClass, (byClass.get(record.failureClass) ?? 0) + 1);
      return {
        category,
        solver,
        attempts: records.length,
        solverSuccesses: records.filter((record) => record.success).length,
        replayVerified: records.filter((record) => record.replayVerified).length,
        failures: failures.length,
        declaredScopeRejections: failures.filter((record) => record.declaredScopeRejection).length,
        failureClasses: Object.fromEntries(byClass),
        totalSolverMs: Math.round(records.reduce((total, record) => total + record.runtimeMs, 0)),
        medianMoveCount: (() => {
          const counts = records.filter((record) => record.replayVerified).map((record) => record.moveCount).sort((a, b) => a - b);
          return counts.length === 0 ? null : counts[Math.floor(counts.length / 2)]!;
        })(),
      };
    });
  });

  console.log('\n=== summary ===');
  console.log('category            solver                  attempts  solved  verified  failed  solver-ms  median-moves');
  for (const row of summary) {
    console.log(
      `${row.category.padEnd(20)}${row.solver.padEnd(24)}${String(row.attempts).padStart(8)}${String(row.solverSuccesses).padStart(8)}${String(row.replayVerified).padStart(10)}${String(row.failures).padStart(8)}${String(row.totalSolverMs).padStart(11)}${String(row.medianMoveCount ?? '-').padStart(14)}`,
    );
  }

  /**
   * Per additional atom `a`, a decision about `a in G`:
   *
   * - `in-G-certified`: a solver returned a word `w` of existing atoms and the
   *   replay verified `w . (a . solved) = solved`. H acts faithfully on the
   *   400-cell position+orientation record, so the stabiliser of the solved
   *   state is trivial and `w a = e`, i.e. `a = w^-1 in G`.
   * - `not-in-G-proved`: the state `a . solved` fails a homomorphic invariant
   *   of G, so no word of existing atoms can produce it.
   * - `undetermined`: neither — the solvers did not solve it and no invariant
   *   here rules it out.
   */
  const atomVerdicts = trials
    .filter((trial) => trial.category === 'single-additional')
    .map((trial) => {
      const verified = trial.solves.filter((solve) => solve.replayVerified);
      return {
        atom: trial.label,
        ringSide: trial.atom?.side ?? null,
        supportSize: trial.atom?.supportSize ?? null,
        verdict: verified.length > 0
          ? ('in-G-certified' as const)
          : trial.invariant.provablyOutsideG
            ? ('not-in-G-proved' as const)
            : ('undetermined' as const),
        certifyingSolvers: verified.map((solve) => solve.solver),
        shortestVerifiedWord: verified.length === 0 ? null : Math.min(...verified.map((solve) => solve.moveCount)),
        invariantEvidence: trial.invariant.orbitConsistent
          ? trial.invariant.parityInSpan
            ? 'both invariants satisfied (no obstruction found)'
            : `orbit-wise parity vector 0x${trial.invariant.parityMask.toString(16)} lies outside the F2-span of the 468 generators`
          : `${trial.invariant.offOrbitCells} cells sit outside their home site's G-orbit`,
      };
    });
  const certificates = atomVerdicts.filter((entry) => entry.verdict === 'in-G-certified');
  const refutations = atomVerdicts.filter((entry) => entry.verdict === 'not-in-G-proved');
  console.log(
    `\nsingle-atom membership decisions over ${atomVerdicts.length} additional atoms: ` +
      `${certificates.length} certified in G (solver word, replay-verified), ` +
      `${refutations.length} proved outside G (invariant), ` +
      `${atomVerdicts.length - certificates.length - refutations.length} undetermined`,
  );

  console.log(
    '\nNote: every success above is a constructive membership certificate for that one state. ' +
      'A finite set of successes is not a completeness proof — neither that G = H, nor that the solvers ' +
      'cover every state of either model.',
  );

  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    outPath,
    `${JSON.stringify(
      {
        level,
        generatedAt: new Date().toISOString(),
        pilot,
        counts: { existingAtoms: existingAtoms.length, additionalAtoms: additionalAtoms.length },
        invariants: {
          orbitSizes: invariants.orbitSizes,
          parityRank: invariants.parityRank,
          note:
            'Site orbits and orbit-wise permutation parity are homomorphic invariants of G. Failing either proves a ' +
            'state is outside G; passing both proves nothing (orientation freedom is not tested).',
        },
        warmMs: Math.round(warmMs),
        categoryTimingsMs: Object.fromEntries([...categoryTimings].map(([key, value]) => [key, Math.round(value)])),
        summary,
        singleAtomVerdicts: atomVerdicts,
        membershipCertificates: certificates,
        trials,
        completenessCaveat:
          'A finite set of successful trials is not a completeness proof for either model: it certifies membership ' +
          'for the states actually tested and nothing more.',
      },
      null,
      2,
    )}\n`,
  );
  console.log(`\nwrote ${outPath}`);
};

await main();
